FROM --platform=linux/amd64 public.ecr.aws/lambda/python:3.9

# ARG DEBIAN_FRONTEND=noninteractive

# RUN yum update -y
# RUN yum update -y python3 curl libcom_err ncurses expat libblkid libuuid libmount
# RUN yum install ffmpeg libsm6 libxext6 python3-pip git -y

COPY requirements.txt ./requirements.txt

RUN pip install -r ./requirements.txt

ENV PYTHONPATH="${PYTHONPATH}:/app"

WORKDIR /app

COPY app .

CMD [ "main.handler" ]
